### ISSUE TITLE
OPC UA

### ISSUE THREAD

**Issue by apfelsaft87** [Feilner/homebridge-plc#39]
Hi Guys,

thank you for your great work. I will test the functions these days. Actually I'am using node-red and a OPC-UA node to use the integrated OPC Server to communicate with the plc. 

It would be great if you also add OPC support. The connection is much easier and safer than put/get communication.

Thanks again!

**Comment by Feilner** [comment]
Hello,

Actually I have no plans in supporting OPC UA but basically it should be possible. My current plans is to work on a configuration UI. 
You are invited to integrate the OPV UA. I can give you some support. But the main purpose if homebridge-plc was to support my home automation. 

Best regards 

Feilner

Am Mo, 13. Jun 2022, um 15:23, schrieb apfelsaft87:

**Comment by apfelsaft87** [comment]
Hello,
yes I will have a look into the code and try my first steps to integrate OPC UA.
Can you give me some better contact so I can ask you some things outside of github.
Thank you!
